# Generated by Django 5.0 on 2023-12-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filomenas', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='estadia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filomenas.estadia'),
        ),
    ]
